# Use Dynaconf with this to set up your secrets (not to be committed in git, only use locally)
# when initialise, this should be renamed to .secrets.toml

# example
SECRET = 'password'

# usage:
# from conf.config import conf
# print(conf.secret) or print (conf['secret'])