name: Test Copier Template

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-copier-template:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Install uv
        run: |
          pip install uv
          uv sync

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Install PowerShell and Just
        run: |
          sudo apt update
          sudo apt install -y powershell
          sudo apt install just
        shell: bash

      - name: Test template copying
        run: |
          # Create a temporary directory for testing
          TEMP_DIR=$(mktemp -d)
                    
          # Try to copy the template to the temp directory
          echo "Testing copier copy operation..."
          uvx copier copy --trust https://github.com/actuaristai/template.git $TEMP_DIR --vcs-ref=$GITHUB_SHA --data "project_name=check" --data "full_name=Test" --data "email=test" --data "project_short_description=lala" --data "remote_repository=git" 
          
          # Check if copying was successful
          if [ $? -eq 0 ]; then
            echo "✅ Template copied successfully!"
            
            # Validate the generated project
            echo "Validating generated project structure..."
            if [ -f "$TEMP_DIR/README.md" ]; then
              echo "✅ Basic project structure appears valid."
            else
              echo "❌ Generated project doesn't have expected files."
              exit 1
            fi
            
            # Verify the project name was used correctly
            if grep -q "check" "$TEMP_DIR/README.md" || grep -q "check" "$TEMP_DIR/pyproject.toml"; then
              echo "✅ Project name 'check' was used correctly in the generated files."
            else
              echo "❌ Project name 'check' was not found in the expected files."
              exit 1
            fi
          else
            echo "❌ Copier template failed!"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
